version: '3'
services:
  postgres:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=user_db
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

