spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: test
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000
  jpa:
    generate-ddl: true

security:
  jwt:
    refreshTokenExpiration: 150000

server:
  port: 8282
